// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingController from "./booking_controller"
application.register("booking", BookingController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HotkeysActionsController from "./hotkeys_actions_controller"
application.register("hotkeys-actions", HotkeysActionsController)

import TranslateController from "./translate_controller"
application.register("translate", TranslateController)
